### PR TITLE
Best of archives creators/worktypes

### PR DESCRIPTION
**Pull request by tvc15brian**
@jsimic new Creators and workTypes for Best of Archives

### CODE REVIEW

**Comment by sseymore** [comment]
@tvc15brian I need to merge with master, so can you go back to see why this is failing?

**Comment by tvc15brian** [comment]
@sseymore Not sure. I noticed that the pull request just before mine failed as well. I'll take a look at my changes.....
https://travis-ci.org/OregonDigital/opaque_ns/builds/54594771

**Comment by tvc15brian** [comment]
@sseymore Travis says that there was an unexpected token around line 34684 which is at the entry for "Loebl, Schlossman and Bennett". Not sure if it's seeing a hidden character or something - I can't see any problems. That was the same issue with the previous failed pull request.

**Comment by sseymore** [comment]
@tvc15brian I'm not sure what's wrong with that entry either but it was merged by me: https://github.com/OregonDigital/opaque_ns/pull/145 

@jsimic can we reopen this and check to see what's the issue?

I think we should check on that first and just delete all the pull requests and re-do- unless there's an easier way. I have all my new URIs locally so I can just paste them in after your URIs are added and merged. Can you go to your local creator file and copy your URIs out?

**Comment by tvc15brian** [comment]
@sseymore Sounds like the fastest way to resolve this to me. I have my URIs copied - feel free to delete the pull requests.

**Comment by sseymore** [comment]
@tvc15brian I'm just going to merge to see.

**Comment by tvc15brian** [comment]
@sseymore 👍🏻

**Comment by sseymore** [comment]
Ok, all good now. I'm going to add my URIs back. Thanks!

**Pull request merged**
